### ISSUE TITLE
Program stops after 4 to 6 combinations

### ISSUE THREAD

**Issue by Roro-Cyr** [henriksb/ZipCrack#4]
Hey, I probably fucked up something, but I was testing this program and it stops immediately after launching.
```
Password matched: aaaaaaaaaa
Combinations tried: 6
Time taken: 0.000539 seconds
Password matched: aaaaaaaaaf
Combinations tried: 6
Time taken: 0.000539 seconds
Password matched: aaaaaaaaac
Combinations tried: 6
Time taken: 0.000539 seconds
Password matched: aaaaaaaaab
Combinations tried: 6
Time taken: 0.000539 seconds
Password matched: aaaaaaaaad
Combinations tried: 6
Time taken: 0.000539 seconds
Password matched: aaaaaaaaae
Combinations tried: 6
Time taken: 0.000539 seconds
Total combinations tried: 6 in 0.002657 seconds
```

Do you know what my problem might be?

**Comment by henriksb** [comment]
Hey, you are absolutely right. I recently updated the code, which messed up the bruteforce feature. Version 1 should work fine, but a little slower. I'll try to resolve the issue later today.

**Comment by henriksb** [comment]
Hey, I believe it is fixed now. The "Total combinations" is currently wrong, that is because of the threading. This is more a quick release to fix the program, as it was unusable. Please let me know if you have any problems!
